## vars on ansible host
ansibleHostUser: ec2-user
playbookName: jenkins
# the following path includes the playbook name
pathToPlaybbok: "/home/{{ansibleHostUser}}/workbench/vDevOps/{{playbookName}}/"
pathToScripts: "{{pathToPlaybbok}}scripts/"
pathToKey: /home/ec2-user/.ssh/a-scap.pem
##

## vars on remote hosts
# common
dockerUserGroup: docker
# on CentOS
centRemoteUser: centos
# on Ubuntu
ubunRemoteUser: ubuntu
##

uname-s: Linux
uname-m: x86_64
lsbRelease: xenial
figerprintKey: 0EBFCD88
dockerUserGroup: docker
dockerUserName: ubuntu

internalMappingPort1: 8080
externalMappingPort1: 8080

internalMappingPort2: 50000
externalMappingPort2: 50000

jenkinsContainerName: myJenkins
mappedDirectory: jenkinsData

pathToUserHome: /home/
figerprintKey: 0EBFCD88
