---
# tasks file for roles/kube-master

- name: configure /etc/etcd/etcd.conf 
  template:
    src: etc-etcd-etcd.j2
    dest: /etc/etcd/etcd.conf

- name: configure  /etc/kubernetes/apiserver
  template:
    src: etc-kubernetes-apiserver.j2
    dest:  /etc/kubernetes/apiserver

- name: start etcd service
  service:
    name: etcd
    state: started

- name: create the overlay network
  command: etcdctl mkdir /kube-centos/network

- name: configure the overlay network
  shell: | 
    etcdctl mk /kube-centos/network/config "{ \"Network\": \"172.30.0.0/16\", \"SubnetLen\": 24, \"Backend\": { \"Type\": \"vxlan\" } }"

- name: Configure flannel to overlay Docker network in /etc/sysconfig/flanneld on the master
  template:
    src: etc-sysconfig-flanneld.j2
    dest: /etc/sysconfig/flanneld

- name: start etcd kube-apiserver kube-controller-manager kube-scheduler flanneld services
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - etcd
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - flanneld